[program:orion-mqtt]
process_name=%(program_name)s
command=php /var/www/orion/artisan mqtt:subscribe
directory=/var/www/orion
numprocs=1
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/orion/storage/logs/mqtt.log
stopwaitsecs=10
