export const UNIT_CATEGORIES = {
    oht: {
        label: 'OHT – Off-Highway Truck',
        abbr: 'OHT',
        color: 'var(--color-unit-oht)',
        dark: 'var(--color-unit-oht)',
        models: [
            'CAT 777G',
            'CAT 773G',
            'CAT 785D',
            'Komatsu HD785-8',
            'Komatsu HD465-7E0',
            'Liebherr T 284',
            'Hitachi EH5000AC-3',
        ],
    },
    dt: {
        label: 'DT – Dump Truck',
        abbr: 'DT',
        color: 'var(--color-unit-dt)',
        dark: 'var(--color-unit-dt)',
        models: [
            'Hino 500 FM260TI',
            'Hino 500 FM320TI',
            'Mercedes Actros 4045',
            'Scania R500',
            'Volvo FMX 460',
            'MAN TGS 40.440',
        ],
    },
    dozer: {
        label: 'Dozer – Bulldozer',
        abbr: 'DZ',
        color: 'var(--color-unit-dozer)',
        dark: 'var(--color-unit-dozer)',
        models: [
            'CAT D10T2',
            'CAT D8T',
            'CAT D6T',
            'Komatsu D155AX-8',
            'Komatsu D375A-8',
            'Komatsu D65EX-18',
        ],
    },
    excavator: {
        label: 'Excavator',
        abbr: 'EX',
        color: 'var(--color-unit-excavator)',
        dark: 'var(--color-unit-excavator)',
        models: [
            'CAT 390F L',
            'CAT 6060FS',
            'Komatsu PC2000-11',
            'Komatsu PC800SE-11',
            'Hitachi EX2600-7',
            'Liebherr R 9400 G8',
        ],
    },
    grader: {
        label: 'Grader – Motor Grader',
        abbr: 'GR',
        color: 'var(--color-unit-grader)',
        dark: 'var(--color-unit-grader)',
        models: [
            'CAT 16M3',
            'CAT 14M3',
            'CAT 12M3',
            'Komatsu GD825A-2',
            'Komatsu GD655-7',
        ],
    },
    compactor: {
        label: 'Compactor – Road Roller',
        abbr: 'CP',
        color: 'var(--color-unit-compactor)',
        dark: 'var(--color-unit-compactor)',
        models: [
            'CAT CS56B',
            'CAT CP56B',
            'Bomag BW 219 DH-5',
            'Dynapac CA2500',
        ],
    },
    driller: {
        label: 'Driller – Drill Rig',
        abbr: 'DR',
        color: 'var(--color-unit-driller)',
        dark: 'var(--color-unit-driller)',
        models: [
            'CAT MD6250',
            'Atlas Copco PV351',
            'Sandvik DR461i',
            'Epiroc PitViper 271',
        ],
    },
    other: {
        label: 'Other',
        abbr: '?',
        color: 'var(--color-unit-other)',
        dark: 'var(--color-unit-other)',
        models: [],
    },
} as const;

export type UnitCategory = keyof typeof UNIT_CATEGORIES;
